// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('cocacola', async function() {
    // Test name: cocacola
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 690x801 | 
    await driver.manage().window().setRect({ width: 690, height: 801 })
    // 3 | click | css=.ng-scope:nth-child(1) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .input-group-append > .btn")).click()
    // 4 | click | css=.ng-scope:nth-child(1) > td .form-control | 
    await driver.findElement(By.css(".ng-scope:nth-child(1) > td .form-control")).click()
    // 5 | assertText | css=tr:nth-child(4) > .ng-binding | €1.25
    assert(await driver.findElement(By.css("tr:nth-child(4) > .ng-binding")).getText() == "€1.25")
    // 6 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 7 | assertText | css=.ng-binding:nth-child(4) | €1.25
    assert(await driver.findElement(By.css(".ng-binding:nth-child(4)")).getText() == "€1.25")
    // 8 | runScript | window.scrollTo(0,0) | 
    await driver.executeScript("window.scrollTo(0,0)")
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 10 | assertText | css=p | Coming right up! ~bzzzt~
    assert(await driver.findElement(By.css("p")).getText() == "Coming right up! ~bzzzt~")
  })
  it('onebeer-Test1', async function() {
    // Test name: onebeer-Test1
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1098x841 | 
    await driver.manage().window().setRect({ width: 1098, height: 841 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | assertText | css=.ng-binding:nth-child(4) | €2.00
    assert(await driver.findElement(By.css(".ng-binding:nth-child(4)")).getText() == "€2.00")
    // 7 | type | id=ageInput | 12
    await driver.findElement(By.id("ageInput")).sendKeys("12")
    // 8 | assertValue | id=ageInput | 12
    {
      const value = await driver.findElement(By.id("ageInput")).getAttribute("value")
      assert(value == "12")
    }
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 10 | assertText | css=.alert-danger > .alert-heading | Prrt!
    assert(await driver.findElement(By.css(".alert-danger > .alert-heading")).getText() == "Prrt!")
  })
  it('onebeer-Test2', async function() {
    // Test name: onebeer-Test2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1098x841 | 
    await driver.manage().window().setRect({ width: 1098, height: 841 })
    // 3 | click | css=.ng-scope:nth-child(2) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(2) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | assertText | css=.ng-binding:nth-child(4) | €2.00
    assert(await driver.findElement(By.css(".ng-binding:nth-child(4)")).getText() == "€2.00")
    // 7 | type | id=ageInput | 21
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 8 | assertValue | id=ageInput | 21
    {
      const value = await driver.findElement(By.id("ageInput")).getAttribute("value")
      assert(value == "21")
    }
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 10 | assertText | css=p | Coming right up! ~bzzzt~
    assert(await driver.findElement(By.css("p")).getText() == "Coming right up! ~bzzzt~")
  })
  it('onewine-Test1', async function() {
    // Test name: onewine-Test1
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1098x841 | 
    await driver.manage().window().setRect({ width: 1098, height: 841 })
    // 3 | click | css=.ng-scope:nth-child(3) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | assertText | css=.ng-binding:nth-child(4) | €3.00
    assert(await driver.findElement(By.css(".ng-binding:nth-child(4)")).getText() == "€3.00")
    // 7 | type | id=ageInput | 12
    await driver.findElement(By.id("ageInput")).sendKeys("12")
    // 8 | assertValue | id=ageInput | 12
    {
      const value = await driver.findElement(By.id("ageInput")).getAttribute("value")
      assert(value == "12")
    }
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 10 | assertText | css=.alert-danger > .alert-heading | Prrt!
    assert(await driver.findElement(By.css(".alert-danger > .alert-heading")).getText() == "Prrt!")
  })
  it('onewine-Test2', async function() {
    // Test name: onewine-Test2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1098x841 | 
    await driver.manage().window().setRect({ width: 1098, height: 841 })
    // 3 | click | css=.ng-scope:nth-child(3) > td .input-group-append > .btn | 
    await driver.findElement(By.css(".ng-scope:nth-child(3) > td .input-group-append > .btn")).click()
    // 4 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 5 | click | id=ageInput | 
    await driver.findElement(By.id("ageInput")).click()
    // 6 | assertText | css=.ng-binding:nth-child(4) | €3.00
    assert(await driver.findElement(By.css(".ng-binding:nth-child(4)")).getText() == "€3.00")
    // 7 | type | id=ageInput | 21
    await driver.findElement(By.id("ageInput")).sendKeys("21")
    // 8 | assertValue | id=ageInput | 21
    {
      const value = await driver.findElement(By.id("ageInput")).getAttribute("value")
      assert(value == "21")
    }
    // 9 | click | css=.btn-success | 
    await driver.findElement(By.css(".btn-success")).click()
    // 10 | assertText | css=p | Coming right up! ~bzzzt~
    assert(await driver.findElement(By.css("p")).getText() == "Coming right up! ~bzzzt~")
  })
})
